# Generated by Django 4.2.6 on 2023-11-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=9)),
                ('UF', models.CharField(max_length=2)),
                ('CIDADE', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=10)),
                ('ENDERECO', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=14, unique=True)),
                ('NOME', models.CharField(max_length=255)),
                ('STATUS', models.PositiveIntegerField(choices=[(1, 'ATIVO'), (2, 'DESATIVADO')], default=1)),
                ('DATA_FUNDACAO', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=75)),
                ('SENHA', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=15, unique=True)),
                ('STATUS', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solidify.usuario')),
                ('PRIVILEGIO', models.CharField(choices=[('A', 'ADMIN'), ('U', 'USER')], default=True)),
                ('ID_ONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solidify.ong')),
            ],
            bases=('solidify.usuario',),
        ),
    ]
