# Generated by Django 4.2.6 on 2023-11-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solidify.usuario')),
                ('CEP', models.CharField(max_length=9)),
                ('UF', models.CharField(max_length=2)),
                ('CIDADE', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=10)),
                ('ENDERECO', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('solidify.usuario', models.Model),
        ),
        migrations.AddField(
            model_name='usuario',
            name='TIPO',
            field=models.CharField(choices=[('A', 'ADMIN'), ('V', 'VOLUNTARIO')], default=True),
        ),
    ]
