# Generated by Django 4.2.6 on 2023-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0002_voluntario_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='PRIVILEGIO',
            field=models.CharField(choices=[('A', 'ADMIN'), ('U', 'USER')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TIPO',
            field=models.CharField(choices=[('A', 'ADMIN'), ('V', 'VOLUNTARIO')]),
        ),
    ]
