# Generated by Django 4.2.6 on 2023-11-22 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0003_alter_administrador_privilegio_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='DATA_NASC',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
