# Generated by Django 4.2.6 on 2023-11-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0004_voluntario_data_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=9)),
                ('UF', models.CharField(max_length=2)),
                ('CIDADE', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=10)),
                ('ENDERECO', models.CharField(max_length=255)),
                ('TITULO', models.CharField(max_length=255)),
                ('DESCRICAO', models.CharField(max_length=1000)),
                ('DATA_REALIZACAO', models.DateField()),
                ('STATUS', models.BooleanField(default=True)),
                ('NR_VOLUNTARIO', models.IntegerField()),
                ('DATA_CANCELAMENTO', models.DateField(null=True)),
                ('MOTIVO_CANCELAMENTO', models.CharField(max_length=1000, null=True)),
                ('ID_ADMINISTRADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solidify.administrador')),
                ('ID_ONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solidify.ong')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voluntarios_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=255)),
                ('CARGO', models.CharField(max_length=60)),
                ('ID_EVENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solidify.evento')),
                ('ID_ONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solidify.ong')),
                ('ID_VOLUNTARIO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solidify.voluntario')),
            ],
        ),
    ]
