# Generated by Django 4.2.6 on 2023-11-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0005_evento_voluntarios_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='NR_VOLUNTARIO',
            new_name='NR_VOLUNTARIOS',
        ),
    ]
