# Generated by Django 4.2.6 on 2023-11-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0007_alter_voluntarios_evento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntario',
            old_name='score',
            new_name='SCORE',
        ),
    ]
