# Generated by Django 4.2.6 on 2023-11-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0008_rename_score_voluntario_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='CNPJ',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
