# Generated by Django 4.2.6 on 2023-12-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0009_alter_ong_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntarios_evento',
            name='CPF_VOLUNTARIO',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
