# Generated by Django 4.2.6 on 2023-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0010_voluntarios_evento_cpf_voluntario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarios_evento',
            name='CPF_VOLUNTARIO',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
