# Generated by Django 4.2.6 on 2023-12-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidify', '0012_alter_voluntarios_evento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ONG_NOME',
            field=models.CharField(default='Dulce Maria', max_length=255),
            preserve_default=False,
        ),
    ]
