databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: 'django-insecure-*7jccdmcfrev5!9)kj8h_g_*8d-vh=m1-+lv0mw%g=14!ss&v='
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4